### ISSUE TITLE
Fix redirect to the www domain for `https://bootstrapcdn.com`

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#1074]
We need to find a way to listen on the naked domain's address too on Heroku.

https://bootstrapcdn.com should redirect to https://www.bootstrapcdn.com

This is an important issue, and needs to be addressed once and for all.

Opening this to track it separately from #700 

/CC @jmervine

**Comment by XhmikosR** [comment]
Since I don't have access on Heroku nor AWS myself, can someone tell us where the problem is exactly?

If there's a proper DNS entry for both `www` and naked domain, and they both point to the same Heroku app, then it should work.

https://devcenter.heroku.com/articles/route-53

So, if the problem is Route 53, then we really need to switch registrars.

**Comment by jimaek** [comment]
Fixed

**Comment by XhmikosR** [comment]
Woot, thanks!

**Comment by XhmikosR** [comment]
Actually @jimaek can you also set an HSTS header? If SSL is automated we can go with 1 year and preload. so that we can move with #700.
