### ISSUE TITLE
Make deployments more foolproof

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#1109]
@jmervine: it's your area of expertise since you only have access there. There must be some way we make a retry or something to prevent deployments not happening.

Because, I just happened to notice it and this could be very problematic.

**Comment by jmervine** [comment]
Let me know next time this happens and I'll check the build history and see if heroku even got notified. If it did and failed it should be posted on #notifications in Slack, if not, then it's a breakdown either in github sending the webhook, travis notifying that it succeeded or heroku actually getting the notifications. Regardless, as mentioned in slack, we can can't alert or retry when no action is recorded. 

I can always manually trigger a build from the heroku dashboard via my phone, worst case.

**Comment by XhmikosR** [comment]
I thought the failure was in `npm i` step or something hence why I believe there's room for improvement. Maybe a retry after an interval just to work around failures in this step.

If the hook failed for some reason, there's not a lot we can do, I get that.

**Comment by XhmikosR** [comment]
@jmervine: did you disable the CI check requirement for deployments? If so maybe we can close this.
