### ISSUE TITLE
New page: Books

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrapcdn#1128]
Using Google Book Search, I've been finding notable authors/publishers referencing BootstrapCDN. For example:

* [O'Reilly Media - Building Progressive Web Apps: Bringing the Power of Native to the Browser](https://books.google.com/books?id=H8o0DwAAQBAJ&printsec=frontcover&dq=BootstrapCDN&hl=en&sa=X&ved=0ahUKEwj0t72wspfbAhVL7mMKHaZFD5I4FBDoAQhaMAg#v=onepage&q=BootstrapCDN&f=false)
* [Wiley - Coding for Dummies](https://books.google.com/books?id=0f9BDAAAQBAJ&q=BootstrapCDN#v=snippet&q=BootstrapCDN&f=false)
* [Sams Publishing - Boostrap in 24 Hours](https://books.google.com/books?id=F3_eCgAAQBAJ&printsec=frontcover&dq=BootstrapCDN&hl=en&sa=X&ved=0ahUKEwjMgoihtJfbAhVY5WMKHTX3B9Q4HhDoAQg3MAI#v=onepage&q=BootstrapCDN&f=false)

and [many more](https://www.google.com/search?tbm=bks&q=BootstrapCDN+)...

We could use Affiliate Links to raise money for the our [Open Source Collective](https://opencollective.com/getbootstrapcdn)

- [x] Pick 4 books (to start)
- [x] Mockup page (same layout as [showcase](https://www.bootstrapcdn.com/showcase/))
- [x] Decide to add affiliate links or not

**Book 1**
```
<a href="https://www.amazon.com/Jump-Start-Bootstrap-Speed-Weekend/dp/0992279437/ref=as_li_ss_il?_encoding=UTF8&psc=1&refRID=2WP7MEQ0KPAHQS6YT117&linkCode=li3&tag=bcdn-20&linkId=b44f87f6e04d5eb7e6b49af61cd0e422" target="_blank"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=0992279437&Format=_SL250_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=bcdn-20" ></a><img src="https://ir-na.amazon-adsystem.com/e/ir?t=bcdn-20&l=li3&o=1&a=0992279437" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
```

**Book 2**
```
<a href="https://www.amazon.com/Building-Progressive-Web-Apps-Bringing-ebook/dp/B075HP52WY/ref=as_li_ss_il?ie=UTF8&linkCode=li3&tag=bcdn-20&linkId=013ca3a2eb57883d255384829ec0a6a2" target="_blank"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B075HP52WY&Format=_SL250_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=bcdn-20" ></a><img src="https://ir-na.amazon-adsystem.com/e/ir?t=bcdn-20&l=li3&o=1&a=B075HP52WY" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
```

**Book 3**
```
<a href="https://www.amazon.com/Coding-Dummies-Computer-Tech/dp/1119293324/ref=as_li_ss_il?ie=UTF8&linkCode=li3&tag=bcdn-20&linkId=fb405dc117a040e91557b45f6dc1094b" target="_blank"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=1119293324&Format=_SL250_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=bcdn-20" ></a><img src="https://ir-na.amazon-adsystem.com/e/ir?t=bcdn-20&l=li3&o=1&a=1119293324" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
```

**Book 4**
```
<a href="https://www.amazon.com/Bootstrap-Hours-Sams-Teach-Yourself-ebook/dp/B017M8OWZQ/ref=as_li_ss_il?ie=UTF8&linkCode=li3&tag=bcdn-20&linkId=f8a39275b5204f5f2d0427a1ef1c4f83" target="_blank"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B017M8OWZQ&Format=_SL250_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=bcdn-20" ></a><img src="https://ir-na.amazon-adsystem.com/e/ir?t=bcdn-20&l=li3&o=1&a=B017M8OWZQ" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
```

**Comment by XhmikosR** [comment]
1. I think we need an image preview for each book
2. New page title + description
3. Should I add it in the navbar?

**Comment by jdorfman** [comment]
Weird are they not showing up for you?

![image](https://user-images.githubusercontent.com/398230/40577077-6e365520-60b4-11e8-9aa5-c25d6fca903a.png)

2. 
* Title: Bootstrap Books
* Desc:  Books that feature BootstrapCDN.

3. Yes, please. We will be playing around with different links around the site to see what works best so it most likely won't be permanent.

**Comment by XhmikosR** [comment]
1. They weren't showing up when I wrote this because they were blocked by CSP then
2 and 3. OK

I was thinking. Will attribution work if we don't use this exact markup? For example the current solution works fine in normal mode, but on incognito mode no image is shown. We could work around this by hosting the images ourselves and using the link only.
