### ISSUE TITLE
Move CDN files to `/cdn/`

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#1140]
The current situation is a bit messy IMO. Also, it shows us down, not a lot but it's noticeable in tests.

@jmervine @jdorfman what do you guys think? Preview: https://github.com/MaxCDN/bootstrapcdn/tree/develop-xmr-mv-cdn-files

**Comment by jdorfman** [comment]
That actually isn't such a bad idea. Makes more sense IMO. @jmervine thoughts?

**Comment by XhmikosR** [comment]
@jdorfman: see also the relevant PR #1146
