### ISSUE TITLE
Promote jobs page

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrapcdn#1157]
```html
<div class="alert alert-warning text-center" role="alert">
    Looking for a new gig? Check out our <a href="/jobs/">jobs page</a>!
</div>
```

![image 2018-05-29 at 8 00 37 am](https://user-images.githubusercontent.com/398230/40667254-84e332ca-6316-11e8-87ae-50d8b2876983.png)

**Comment by jdorfman** [comment]
**Mobile view:**
![image](https://user-images.githubusercontent.com/398230/40727349-8e7a2a5c-63dc-11e8-8399-a33d00b1dac2.png)

**Reasons:**
* Mobile traffic: only 1.49% (April 2018)
* Site is useless on mobile. I.e. no one is coding on their phone.

**Comment by XhmikosR** [comment]
@jdorfman: any reason why we shouldn't show the alert to the top on desktop too? It would certainly be simpler.

**Comment by jdorfman** [comment]
@XhmikosR yeah sure why not. Any chance it can get pushed out in like an hour?
