### ISSUE TITLE
Font awesome 5.1.0

### ISSUE THREAD

**Issue by lonix1** [MaxCDN/bootstrapcdn#1200]
Will this latest 5.x version of FA be supported?

**Comment by jmervine** [comment]
@lonix1 There has been some discussion on that in https://github.com/MaxCDN/bootstrapcdn/pull/909, it looks like the tides were leaning towards yes, but I don't think it's a priority and needs some some UI work to do it in a way that makes sense.

Sorry for the "no answer, answer", but that's kind of where we're at on it, last I discussed with the team.

**Comment by lonix1** [comment]
thanks, I'll comment there
