### ISSUE TITLE
 https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css 0 () (index):638   

### ISSUE THREAD

**Issue by vinaymorkar** [MaxCDN/bootstrapcdn#1203]
Failed to load resource: net::ERR_CONNECTION_RESET

**Comment by XhmikosR** [comment]
If this is a CDN service related issue (timeouts, slowness, ssl), please fill out this form so we can debug it: <https://goo.gl/forms/u2SFZS44ZGIM7yP82>

**Comment by DmMhs** [comment]
I have same problem with 3.3.7 version and my website. And I also have this problem with bootstrap cdn site (https://www.bootstrapcdn.com/). I can see no styling - just bold html structure. Error messages:
codefund.io/scripts/c6a10903-6a7f-435b-92b2-99c9c9ce3379/embed.js?target=codefund&theme=bootstrapcdn:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
stackpath.bootstrapcdn.com/bootswatch/4.1.3/cosmo/bootstrap.min.css:1 Failed to load resource: net::ERR_CONNECTION_RESET
stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js:1 Failed to load resource: net::ERR_CONNECTION_RESET
My browser is Google Chrome v71.0.3578.98

**Comment by XhmikosR** [comment]
https://github.com/MaxCDN/bootstrapcdn/issues/1203#issuecomment-409183727
