### ISSUE TITLE
Add codefund "bottom banner" ad code

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrapcdn#1221]
Embed the following script into your website and create a `div` with `id="codefund_ad"`

```
<script src="https://codefund.io/scripts/c6a10903-6a7f-435b-92b2-99c9c9ce3379/embed.js"></script>
<div id="codefund_ad"></div>
```

It will look like this: 
![image](https://user-images.githubusercontent.com/398230/46313373-8e5ee380-c57c-11e8-8085-a7e4cdf1695f.png)

via: https://sweetalert2.github.io/

This will add another ~$200 a month to our OC.

**Comment by XhmikosR** [comment]
Looking at it.
