### ISSUE TITLE
Bootswatch 3 Solar theme is 404

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#1247]
@thomaspark: did you remove that?

**Comment by thomaspark** [comment]
@XhmikosR, yes, Solar was not included in an official release for v3.

**Comment by XhmikosR** [comment]
You mean in the last release because it was definitely there.

@jmervine how do you want to proceed?

**Comment by XhmikosR** [comment]
@jmervine ping for feedback. We could just remove it from the frontend and keep the files in the CDN.

**Comment by XhmikosR** [comment]
Closing since the new 3.4.1 version won't have this. Though I still don't get how we have the files in the first place...
