### ISSUE TITLE
4.2.0 Tasks

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrapcdn#1255]
- [x] Sync to S3 (@jdorfman) 
- [x] Update site (@XhmikosR) 
- [x] Run Scripts (@jmervine)

**Comment by jmervine** [comment]
@jdorfman
1. Looks like the site has already been updated on #1256.
2. I've already run the script on 4.2.0, but I'll run it again.
3. Looks like I need to run on 4.2.1 as well using #1256

**Comment by jmervine** [comment]
Oops, I ran it on '3.2.0'. Running on '4.2.0' now and then on '4.2.1'.

**Comment by jmervine** [comment]
Note for the future, running the script also uploads the files, so no need to do that separately.

**Comment by jmervine** [comment]
Done.

**Comment by jmervine** [comment]
I'll let you close this when you're confident it's done.
