### ISSUE TITLE
StackShare Awards

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrapcdn#1266]
The 5th Annual StackShare Awards are almost here! 🎉 To vote for [Bootstrap](https://stackshare.io/bootstrap), show some love by creating or updating your stack by next week, Tuesday January 29th at 11pm PST

https://stackshare.io/bootstrap

![speedup-screen-recording-2019-01-23-at-04 42-pm](https://user-images.githubusercontent.com/398230/51715011-f170fc00-1feb-11e9-99dd-65517da2eadd.gif)

**Comment by sahin** [comment]
+1

**Comment by jdorfman** [comment]
Winners: https://stackshare.io/posts/top-developer-tools-2018
