### ISSUE TITLE
JSON API missing bootswatch & bootlint

### ISSUE THREAD

**Issue by markcarver** [MaxCDN/bootstrapcdn#1281]
Hello again 😄

I originally opened #460 a while back and from that, y'all ended up creating:

https://www.bootstrapcdn.com/data/bootstrapcdn.json

This has been fantastic but given the recent changes/overhaul I've been doing in https://www.drupal.org/project/bootstrap/issues/3031415, I'm realizing this data is rather incomplete.

It doesn't contain any of the other package data that this CDN provides (e.g. bootswatch, bootlint).

I see that this JSON file is dynamically generated here:
https://github.com/MaxCDN/bootstrapcdn/blob/develop/lib/helpers.js#L37-L60

**Comment by XhmikosR** [comment]
I don't think we ever cared about other packages.

**Comment by markcarver** [comment]
Maybe so, but given that this is technically a separate CDN and jsDelivr's API no longer provides this info (it used to: https://api.jsdelivr.com/v1/bootstrap/libraries), the ability to determine what this CDN actually provides has been lost.

**Comment by XhmikosR** [comment]
I will consider if it's worth bothering with.

**Comment by markcarver** [comment]
FWIW, I cannot imagine it'd be that difficult to implement given that everything is pretty much already there (config wise)... the missing packages just need to be connected into the existing route.

**Comment by XhmikosR** [comment]
The problem isn't the implementation, obviously.

The problem is this data file is used by other stuff too, like the WP plugin which hasn't been updated for years, nor tested. And I don't want to break that.

**Comment by markcarver** [comment]
https://plugins.trac.wordpress.org/browser/bootstrapcdn/trunk/bootstrapcdn.php#L437

Specifically checks/extracts data for `$cdn_data['bootstrap']` and `$cdn_data['fontawesome']`.

Since these would only be additive (new/separate packages), it shouldn't affect that code in the slightest.

I imagine that if they were to have any issues, it'd actually likely be the [outdated URL](https://plugins.trac.wordpress.org/browser/bootstrapcdn/trunk/bootstrapcdn.php#L24) its still using:
`http://netdna.bootstrapcdn.com/data/bootstrapcdn.json`

---

For the record (and more context), this is primiarly about adding back official support for this CDN to https://www.drupal.org/project/bootstrap.

It had to be previously removed, in favor of, jsDelivr's API/CDN for [stability reasons](https://www.drupal.org/node/2452617).

Partial support was still provided using the [previous jsDelivr API](https://api.jsdelivr.com/v1/bootstrap/libraries), but now that it has been deprecated and no longer updated, there is no longer a complete "list of assets" that this CDN provides.

My [current effort](https://www.drupal.org/project/bootstrap/issues/3031415) makes use of the [newer jsDelivr API](https://github.com/jsdelivr/data.jsdelivr.com), but unfortunately (as mentioned above) it doesn't provide support for this CDN anymore.

While this JSON API does provide the necessary data for Bootstrap, it would be extremely helpful if it could also (at the very least) throw in the Bootswatch data so the "Theme" selector in the base-theme's settings UI could provide more options (automatically) with assets this CDN technically does support.

**Comment by XhmikosR** [comment]
Still, I need to check with the other people, so please wait until then.

Otherwise I have no problem adding this.

**Comment by jmervine** [comment]
It seems like a fairly simple update. I don’t have an issue with it. 

@jdorfman ?

**Comment by XhmikosR** [comment]
@markcarver: please check #1282 and https://bootstrapcdn-dev-pr-1282.herokuapp.com/data/bootstrapcdn.json
