### ISSUE TITLE
Dark variant

### ISSUE THREAD

**Issue by fuzzy76** [MaxCDN/bootstrapcdn#1289]
Some elements (like the hamburger menu icon) won't adapt to dark colors without a recompile. Would it be possible to host a dark variant of bootstrap?

**Comment by XhmikosR** [comment]
We only host vanilla, i.e. unmodified builds of Bootstrap, Bootswatch, etc.

So, I don't think this is something that falls into this project. If such build is made officially available upstream, then we'll also have it.

I hope this solves your question :)
