### ISSUE TITLE
New Sponsor

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrapcdn#1352]
**Name:** EduBirdie
**Link:** https://edubirdie.com/

**Notes:** 
* MUST remove `no-follow`
* Length 2 months

**Mockup:**

<img width="637" alt="Image 2019-08-01 at 10 30 08 AM" src="https://user-images.githubusercontent.com/398230/62314276-7f201f00-b447-11e9-8468-c23b9652c760.png">

**OC donation:** 

![image](https://user-images.githubusercontent.com/398230/62313931-c0fc9580-b446-11e9-9024-f56746040f85.png)

**Comment by XhmikosR** [comment]
I'll need someone to remind me about the 2-month duration.

**Comment by Johann-S** [comment]
Maybe we should use OpenCollective API, instead of having to keep that in mind

**Comment by XhmikosR** [comment]
The thing is that the footer links aren't really sponsors right now. I'm all for automating this, though.

**Comment by jdorfman** [comment]
@XhmikosR I have a calendar event set for 2 months from today
