### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#1359]
@jdorfman @jmervine can you guys sign up for https://github.com/features/actions ?

I'd prefer it if we just used GH Actions CI and removed any third-party services.

**Comment by jmervine** [comment]
```
You’re in the queue for the beta—we’ll let you know as soon as you have access.
```

**Comment by XhmikosR** [comment]
Thanks! Do let me know when it's activated.

**Comment by jdorfman** [comment]
Apparently I have it I just can't enable it on this org

![image](https://user-images.githubusercontent.com/398230/64359582-7ded8f00-cfbd-11e9-8cc4-0d6b0f4fcafe.png)

**Comment by jmervine** [comment]
I was able to select the MaxCDN org.
