### ISSUE TITLE
Is bootstrap CDN down?

### ISSUE THREAD

**Issue by mkamranhamid** [MaxCDN/bootstrapcdn#1368]
I'm trying to access [bootstrap cdn](https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css) but not able to also i didn't have the backup plan for bootstrap so all my websites are pretty messed up. Can anyone please explain whats going on

**Comment by XhmikosR** [comment]
Works fine here. Please fill in https://goo.gl/forms/u2SFZS44ZGIM7yP82

**Comment by mkamranhamid** [comment]
I'm currently using phone I'll fill this form asap I reach workstation because it requires to perform some `curl` commands

**Comment by mkamranhamid** [comment]
Submitted the form

**Comment by mkamranhamid** [comment]
Closing it because it was a downtime for a small time and now working fine.
