### ISSUE TITLE
SUGGESTION: Add query params for colors

### ISSUE THREAD

**Issue by shhdharmen** [MaxCDN/bootstrapcdn#1421]
For example, if I hit: `https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css?primary=%23b11e29` (note query param: **?primary=%23b11e29**), it will load compiled bootstrap themed css file with primary color as #b11e29.

**Comment by XhmikosR** [comment]
Sorry, I don't see us implementing such thing right now.

You are welcome to submit a PR, assuming it doesn't open the doors to XSS

**Comment by shhdharmen** [comment]
Ok. I am not sure how to do that, I will check and submit a PR. Closing this for now.
