### ISSUE TITLE
ISsues with Bootstrap 

### ISSUE THREAD

**Issue by tech-mnet** [MaxCDN/bootstrapcdn#1454]
Dear Stackpath /MaxCDN Team/Bootstrap Team ,
At the onset allow us to introduce ourselves .
We are M-Net Fiber Fast AS132960 , an ISP in North East India. We have written to you many times but our queries have not
been resolved and our esteemed End Customers are facing this issues and as a prominenet player in the IT Space,
I am sure you will understand , how important is providing Impeccable Service to you Clients matter.
But I am extremely sorry to say inspite of e mailing to you so many times , our queries are not getting resolved.
We have mailed you many times with all test results you have asked for , but things are not getting resolved at your end.
Let me take this oppurtunity to please explain the same in detail.
Our AS number is AS132960 and we have the following IP Schemes
103.224.184.0/22
45.115.172.0/22
103.96.48.0/22
The Problem is that when ever we try to access your below URLs , it does not get displayed and shows error.
We have checked by using a lot of tools and even tried VPN like TOR, Surfshark , NordVPN and other it is working fine on
other IPs.
This is clearly a issue with our IP pools being blacklisted by you or blocked , as because through other IP s its working fine.
I have Looped in My esteemed Customers who are marked in this mail.
Mr Lokntah Roy ,( lroy@topcem.in, +917637012153) an extremely talented , versatile , seasoned and Veteran IT professional representing  the IT Domain for his organization and looking after  IT Operations for the said Organization who are regularly facing issues in opening the below mentioned URLs
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js
Request Loknath Sir  for his valuable technical inputs and observations.
Secondly , I have looped in my Sales and Marketing Head ( +919859920504 , saurav@mnetconnect.com) who will explain to you directly how painful for the Customer it is as it hampers thier
day to day Operations.
Thirdly , I have Looped in my Upstream ISP Powergrid and thier NOC Team so that any technical inputs can be provided from thier end.
Mr. Rohit Kumar ( +919873918460 , rohit@powergridindia.com ) and Mr Deewan Singh ( deewan@powergridindia.com , +918826697154)
We sincerely request you to please look into this matter seriously and please get this issue resolved permanently and promptly.
Expecting a immediate revert from your end.

We jointly need to get this resolved.

**Comment by XhmikosR** [comment]
Hello.

I was told by StackPath support team that there's an internal issue tracking this. You should get a reply from them there.

**Comment by tech-mnet** [comment]
WE have got no reply . Pls check and revert

**Comment by XhmikosR** [comment]
Well, I don't want to play the middleman here. They tell me, you don't reply on their emails.

You should really take it up with StackPath's support and make sure you reply to their emails. There's nothing we can do here (we are not StackPath ourselves, and the issue has been forwared to them and in turn they have tried to contact you multiple times).

**Comment by tech-mnet** [comment]
Hi,

PFB Thier Response .
