### ISSUE TITLE
Where can the integrity value of a v3.3.7 Bootswatch theme be found?

### ISSUE THREAD

**Issue by nCubed** [MaxCDN/bootstrapcdn#1463]
We are using a 3.3.7 Bootswatch theme served up from the CDN, using an integrity attribute:

` <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css" integrity="sha384-awusxf8AUojygHf2+joICySzB780jVvQaVCAt1clU3QsyAitLGul28Qxb2r1e5g+" crossorigin="anonymous">`

We would like to use the "slate" theme:

`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/slate/bootstrap.min.css">`

Where can I find the integrity attribute value for the 3.3.7 version of the slate theme?

**Comment by XhmikosR** [comment]
You can use https://www.srihash.org/ for this.

**Comment by XhmikosR** [comment]
Or do it manually:

```sh
openssl dgst -sha384 -binary local-folder/css/bootstrap.min.css | openssl base64 -A
```
