### ISSUE TITLE
Display: Swap Support On @font-face's

### ISSUE THREAD

**Issue by whthT** [MaxCDN/bootstrapcdn#1472]
Hi. Is there a chance to support `font-display:swap` rule for font-awesome font faces or some font faces using in bootstrap like [Google Fonts](https://fonts.google.com/?selection.family=Spartan).

![Screenshot from 2020-02-28 11 16 27](https://user-images.githubusercontent.com/5617385/75522877-06546600-5a1c-11ea-99bb-a5660d770655.png)

**Comment by XhmikosR** [comment]
Not really, no. You should ask for this upstream; we only host the files, unmodified.
