### ISSUE TITLE
Enable x-content-type-options for CSS and JS files

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#1497]
We should discuss adding this to CSS and JS files.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

It seems Google does it for their CDN:

```
C:\Users\XhmikosR\Desktop>curl -ILl https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js
HTTP/2 200
...
x-content-type-options: nosniff
```

**Comment by ScottHelme** [comment]
This seems like a reasonable suggestion 👍

**Comment by Malvoz** [comment]
`x-content-type-options: nosniff` also [enables CORB protection](https://chromium.googlesource.com/chromium/src/+/master/services/network/cross_origin_read_blocking_explainer.md#determining-whether-a-response-is-corb_protected) for the resource types:

> If the response contains `X-Content-Type-Options: nosniff` response header, then the response will be CORB-protected if its `Content-Type` header is one of the following:
> 
> HTML MIME type
> XML MIME type (except `image/svg+xml` which is CORB-exempt as described above)
> JSON MIME type
> `text/plain`

**Comment by XhmikosR** [comment]
BTW it seems Google sends the header for all files, which arguably it would be simpler if we did too...

```
C:\Users\XhmikosR\Desktop>curl -ILl https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png
HTTP/2 200
x-content-type-options: nosniff
```

**Comment by XhmikosR** [comment]
Does anybody have any objection to adding the header for all filetypes instead for only .css and .js?

**Comment by jdorfman** [comment]
nope

**Comment by jdorfman** [comment]
@XhmikosR while they are at it, let's remove 

`x-hello-human: Say hello back! @getBootstrapCDN on Twitter`

**Comment by XhmikosR** [comment]
I made the change myself but I can remove it. Any specific reason?

**Comment by jdorfman** [comment]
@XhmikosR I don't check Twitter anymore and so it's wasted bytes over the wire. You dream come true.

**Comment by XhmikosR** [comment]
@ScottHelme do you know if setting this for all filetypes can be troublesome? I see Google is doing the same and AFAICT browsers should ignore it for filetypes that doesn't apply.

Setting it for all filetypes is simpler, otherwise I could do it for all filetypes it's needed as long as I have a list 🙂
