### ISSUE TITLE
Enable x-xss-protection

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#1498]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

@ScottHelme WDYT about this and #1497?

**Comment by ScottHelme** [comment]
The XXP header is no longer useful as the XSS Auditor/Filter in mainstream browsers have been deprecated. I wouldn't recommend enabling this header now. For more info: https://scotthelme.co.uk/deprecating-xss-reports/

**Comment by XhmikosR** [comment]
Thanks for the reply!

I guess I'll drop this then. Can you also chime in in #1017 please?
