### ISSUE TITLE
Font Files for Bootstrap3.3.6 are throwing CERT Error

### ISSUE THREAD

**Issue by redbirdisu** [MaxCDN/bootstrapcdn#1610]
This is what Chrome tools are showing. 

GET https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/fonts/glyphicons-halflings-regular.woff2 net::ERR_CERT_COMMON_NAME_INVALID

Also get errors while loading CSS and JS but they seems to go away after a while.

**Comment by jdorfman** [comment]
Hi @redbirdisu I'm unable to replicate it myself but I am informing StackPath's support team and they will update us asap.

**Comment by redbirdisu** [comment]
Seems like it resolved by itself. It could be the intermittent issue with certs. I am closing the issue for now.
