### ISSUE TITLE
Was stackpath.bootstrapcdn.com down or slow over the weekend 19 and 20th Sept 2020?

### ISSUE THREAD

**Issue by maheshjwagh** [MaxCDN/bootstrapcdn#1622]
Was stackpath.bootstrapcdn.com down or slow over the weekend 19 and 20th Sept 2020?

**Comment by petarpetrovic** [comment]
Hello @maheshjwagh, thanks for reaching out! We did have an emergency maintenance last week and it’s likely that a small portion of requests towards BootstrapCDN assets were slow during the weekend at times. The maintenance has been completed and everything should be back to normal now.

For more information, you can refer to this Status Page: https://status.stackpath.com/incidents/mwffm95rtp9p

In case you’re still experiencing any kind of issue, feel free to post additional info here in the thread and I’ll be happy to take a look.

**Comment by jimaek** [comment]
We have migrated BootstrapCDN to a new system. If anything looks wrong in the future please open a new Github issue.
