### ISSUE TITLE
Add HSTS, submit to HSTS preload list

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#700]
- [x] Merge #730 
- [x] Add the HSTS header
- [ ] Submit `bootstrapcdn.com` to <https://hstspreload.org/?domain=bootstrapcdn.com>

**Comment by jdorfman** [comment]
@XhmikosR is `HSTS` for the website or the CDN? I think we should consider separating the marketing site from the CDN assets. Thoughts?

**Comment by XhmikosR** [comment]
This is for the website only.

**Comment by jdorfman** [comment]
@XhmikosR word. damn your fast haha

**Comment by ScottHelme** [comment]
For reference, I raised a ticket for enabling HSTS on CDN assets: https://github.com/MaxCDN/bootstrap-cdn/issues/750

**Comment by XhmikosR** [comment]
@jdorfman @jmervine: in order for us to comply with HSTS List Submission prerequisites we need to have both naked and normal domain on the same machine so that we handle the redirect ourselves.

What needs to be done to get things going in that regard?

**Comment by jmervine** [comment]
To add support for the root domain with Heroku, we'll need to setup the dns correctly. There's a Heroku help article on it here...

https://devcenter.heroku.com/articles/custom-domains#add-a-custom-root-domain

Also worth looking at...

https://devcenter.heroku.com/articles/apex-domains

**Comment by ScottHelme** [comment]
You could speak with Lucas directly to see if they can make an exception to the standard submission process to get you on the preload list with less friction.

**Comment by XhmikosR** [comment]
@jmervine @jdorfman: Who has access to the DNS site?

I'm not familiar with Heroku and the implications, and generally I just use naked domains (why type more?), but I'm wondering, can't we just add a CNAME pointing to the Heroku IP?

Or otherwise, as @ScottHelme points out, maybe we could bug the HSTS list guys.

**Comment by ScottHelme** [comment]
Given the size and nature of your site, along with the obvious benefits, I'm sure an exception could be made. Let me know if you'd like a direct intro.

**Comment by jmervine** [comment]
@jdorfman Has the contacts for the DNS changes, I believe. Otherwise, I can bug my contact at StackPath.

**Comment by XhmikosR** [comment]
@jmervine @jdorfman: so, what do we do with this?

**Comment by ScottHelme** [comment]
Are you ready to preload? :)

**Comment by XhmikosR** [comment]
Well, I am but I'm not in control of the www domain myself :)

We really need to solve this once and for all and just comply with the
requirements.

**Comment by jdorfman** [comment]
@XhmikosR @ScottHelme @jmervine on the fence. I see this _**possibly**_ affecting SEO which might seem silly, it really isn't because I don't personally pay the bills, in fact, I would be broke beyond belief. I also don't want to bug StackPath to hire an SEO consultant. Bottom line, _at this time_, the trade-off isn't worth it to me.

![image](https://user-images.githubusercontent.com/398230/33232312-da3456cc-d1b8-11e7-9f09-532e1dd98d17.png)

**Comment by XhmikosR** [comment]
This is just wrong. How on earth do you think it affects SEO?

**Comment by jdorfman** [comment]
Everything is indexed and linked to `www.*` If we redirect properly should be fine, if not we lose search rank. I have experienced this in the past, to me I don't think it is worth the risk. If I was paying the bills sure, but I'm not. SEO is an important business value which funds the $30k+ a month needed to sustain this project. Not risking it for HSTS on `www`.

Willing to revisit this in the future, but now, we have bigger issues.

**Comment by XhmikosR** [comment]
Again, you do NOT need to change the redirect.

Please don't close this and be serious with security for once.

**Comment by ScottHelme** [comment]
Maybe I can provide input, I just want to make sure I understand the situation properly. 

Using HSTS (with or without preloading) would only have an impact on http:// -> https:// redirects in that they'd never take place as a compliant client would simply not make the http:// request in the first instance. If you're already redirecting http:// -> https:// then there's really no difference in deploying HSTS or preloading. 

I'm not sure what the worries around the `www.*` are, perhaps you could explain those a little more and I will provide some input. Unless I've missed something, which could well be the case, if you're already redirecting all traffic to https:// for the _entire_ domain (inlcluding all subdomains), preloading won't have an impact on SEO.

It might be worth noting that Cloudflare recently deployed HSTS preloading for their CDN too: https://twitter.com/grittygrease/status/925538203330682881

**Comment by XhmikosR** [comment]
The problem here is that for some unknown reason to me, due to the way things have been set up, the naked domain isn't on the same server as the www domain. Thus we can't do the `http://bootstrapcdn.com/ --> https://www.bootstrapcdn.com/` redirect here.

Now, the HSTS site's error, not sure why it happens, it might be this issue or it's a bug somewhere.

At any case, HSTS should be enabled. I can't emphasize this enough how bad is not to use it.

Thanks @ScottHelme for backing me up here.

**Comment by XhmikosR** [comment]
So basically, the redirect chain currently is:

```
C:\Users\XhmikosR\Desktop>curl -ILl http://bootstrapcdn.com/
HTTP/1.1 301 Moved Permanently
Server: nginx/1.12.1
Date: Sat, 25 Nov 2017 16:37:34 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: http://www.bootstrapcdn.com/

HTTP/1.1 301 Moved Permanently
Server: Cowboy
Connection: keep-alive
Location: https://www.bootstrapcdn.com/
Vary: Accept
Content-Type: text/plain; charset=utf-8
Content-Length: 63
Date: Sat, 25 Nov 2017 16:37:21 GMT
Via: 1.1 vegur

HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
X-Hello-Human: Say hello back! @getBootstrapCDN on Twitter
Cache-Control: public, max-age=0
Last-Modified: Sat, 25 Nov 2017 16:37:22 GMT
Accept-Ranges: bytes
X-Frame-Options: DENY
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Referrer-Policy: strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'; base-uri 'self'; frame-ancestors 'none'; script-src 'self' 'unsafe-inline' maxcdn.bootstrapcdn.com www.google-analytics.com code.jquery.com platform.twitter.com cdn.syndication.twimg.com/timeline/ api.github.com cdn.carbonads.com srv.carbonads.net adn.fusionads.net 'nonce-MjA3ZWQ0NjItZWRiMC00YWY1LWJlNjMtZDAxMTI5ZGRjODYy'; style-src 'self' 'unsafe-inline' maxcdn.bootstrapcdn.com fonts.googleapis.com *.twimg.com platform.twitter.com; img-src 'self' data: www.google-analytics.com bootswatch.com syndication.twitter.com *.twimg.com platform.twitter.com analytics.twitter.com stats.g.doubleclick.net srv.carbonads.net assets.servedby-buysellads.com ad.doubleclick.net *.convertro.com *.c3tag.com *.2mdn.net launchbit.com www.launchbit.com; font-src 'self' maxcdn.bootstrapcdn.com fonts.gstatic.com; frame-src 'self' platform.twitter.com syndication.twitter.com ghbtns.com; child-src 'self' platform.twitter.com syndication.twitter.com ghbtns.com; manifest-src 'self'; report-uri https://d063bdf998559129f041de1efd2b41a5.report-uri.com/r/d/csp/enforce
X-Content-Security-Policy: default-src 'none'; base-uri 'self'; frame-ancestors 'none'; script-src 'self' 'unsafe-inline' maxcdn.bootstrapcdn.com www.google-analytics.com code.jquery.com platform.twitter.com cdn.syndication.twimg.com/timeline/ api.github.com cdn.carbonads.com srv.carbonads.net adn.fusionads.net 'nonce-MjA3ZWQ0NjItZWRiMC00YWY1LWJlNjMtZDAxMTI5ZGRjODYy'; style-src 'self' 'unsafe-inline' maxcdn.bootstrapcdn.com fonts.googleapis.com *.twimg.com platform.twitter.com; img-src 'self' data: www.google-analytics.com bootswatch.com syndication.twitter.com *.twimg.com platform.twitter.com analytics.twitter.com stats.g.doubleclick.net srv.carbonads.net assets.servedby-buysellads.com ad.doubleclick.net *.convertro.com *.c3tag.com *.2mdn.net launchbit.com www.launchbit.com; font-src 'self' maxcdn.bootstrapcdn.com fonts.gstatic.com; frame-src 'self' platform.twitter.com syndication.twitter.com ghbtns.com; child-src 'self' platform.twitter.com syndication.twitter.com ghbtns.com; manifest-src 'self'; report-uri https://d063bdf998559129f041de1efd2b41a5.report-uri.com/r/d/csp/enforce
X-Webkit-Csp: default-src 'none'; base-uri 'self'; frame-ancestors 'none'; script-src 'self' 'unsafe-inline' maxcdn.bootstrapcdn.com www.google-analytics.com code.jquery.com platform.twitter.com cdn.syndication.twimg.com/timeline/ api.github.com cdn.carbonads.com srv.carbonads.net adn.fusionads.net 'nonce-MjA3ZWQ0NjItZWRiMC00YWY1LWJlNjMtZDAxMTI5ZGRjODYy'; style-src 'self' 'unsafe-inline' maxcdn.bootstrapcdn.com fonts.googleapis.com *.twimg.com platform.twitter.com; img-src 'self' data: www.google-analytics.com bootswatch.com syndication.twitter.com *.twimg.com platform.twitter.com analytics.twitter.com stats.g.doubleclick.net srv.carbonads.net assets.servedby-buysellads.com ad.doubleclick.net *.convertro.com *.c3tag.com *.2mdn.net launchbit.com www.launchbit.com; font-src 'self' maxcdn.bootstrapcdn.com fonts.gstatic.com; frame-src 'self' platform.twitter.com syndication.twitter.com ghbtns.com; child-src 'self' platform.twitter.com syndication.twitter.com ghbtns.com; manifest-src 'self'; report-uri https://d063bdf998559129f041de1efd2b41a5.report-uri.com/r/d/csp/enforce
Content-Type: text/html; charset=utf-8
Content-Length: 35135
Vary: Accept-Encoding
Date: Sat, 25 Nov 2017 16:37:22 GMT
Via: 1.1 vegur

```

**Comment by ScottHelme** [comment]
OK so you jump from `http://bootstrapcdn.com/` straight to `https://www.bootstrapcdn.com/` in one redirect. If you want an ideal deployment of the HSTS header in the longer term I'd recommend:

    http://bootstrapcdn.com --> https://bootstrapcdn.com -->https://www.bootstrapcdn.com

You'd set HSTS on the 2nd redirect with includeSubDomains to catch all subdomains.

But anyway, I digress, even in the current setup HSTS (and preloading) wouldn't have any impact but you do seem to have a problem in that I can't connect to `bootstrapcdn.com` on 443 right now:

    scott@Middle-Earth:~$ curl -I https://bootstrapcdn.com
    ^C

    scott@Middle-Earth:~$ openssl s_client -connect boostrapcdn.com:443
    connect: Connection refused
    connect:errno=111

https://securityheaders.io/?q=https%3A%2F%2Fbootstrapcdn.com

Is that supposed to be the case?

**Comment by XhmikosR** [comment]
It's the same technical reasons that this fails as far as I know.

Everything would be much simpler if we handled all redirects ourselves on one host.

**Comment by ScottHelme** [comment]
Redirects and splitting across hosts aside right now, that's a pretty big issue. You aren't answering for your bare domain on https:// at all as far as I can see. You really need to fix that and it's a blocker for preloading too.

**Comment by XhmikosR** [comment]
Unfortunately, it's not something I'm in control of, otherwise the issue wouldn't exist...

Previously it worked with random tools/services being used to make the redirect IIRC. And it was dropped because if I remember correctly, "Who visits the non-www site?". Not my action either.

**Comment by XhmikosR** [comment]
@jdorfman: can we get this sorted with StackPath too? It's really important that we fix the redirect issue; it's not an issue of SEO.

**Comment by jimaek** [comment]
Added headers and submitted for inclusion at https://hstspreload.org/

**Comment by XhmikosR** [comment]
Perfect, closing then !
