### ISSUE TITLE
Add privacy policy page

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#864]
/CC @jdorfman

**Comment by jdorfman** [comment]
Once James comes back from Black Hat I will work with him on this. The tricky thing here is there is `www` and `cdn` which need to be treated separately.

Back in January of 2016 a concerned user emailed MaxCDN support asking about BootstrapCDN's privacy policy. After a few back and forths, we came up with the following (that he then posted on his website):

> Certain elements of the site (such as styles or scripts) may be served by BootstrapCDN, a service of MaxCDN. Each time you access a portion of the site that includes such elements, BootstrapCDN records certain information about your computer or device, including the IP address, geographical location (determined based on the IP address), and your browser's user agent information (which typically includes your operating system and browser type/version). We do not receive or have access to that information, but BootstrapCDN may retain it for security, troubleshooting, and/or service improvement purposes. If you have questions about how BootstrapCDN or MaxCDN uses this information, please contact them directly.

I tried to hire him to write our ToS and Privacy Policy but he respectfully declined. Then the acquisition (StackPath + MaxCDN) happened and this project got put on hold.

**Comment by jdorfman** [comment]
I'm thinking just linking to this: https://www.stackpath.com/privacy-statement/

Thoughts @XhmikosR @jmervine

**Comment by jmervine** [comment]
I don't have a strong opinion, I'll leave that you to and James.

**Comment by XhmikosR** [comment]
I don't have a preference either as long as it covers our use case (Google Analytics, Carbonads); no need to stuff that doesn't apply here.

**Comment by jdorfman** [comment]
Footer or Resources drop down?

![cloudapp annotation 2017-11-28 at 10 15 58 am png](https://user-images.githubusercontent.com/398230/33336597-4ad5ddc4-d425-11e7-9480-ec3bb83b9ca0.png)

**Comment by jmervine** [comment]
I'd probably say footer, but not with it's current design. We'd need to move things around first. Maybe...

```

Maintained by...
Homies be...

SP logo | privacy policy

```

or something of the like.


That said, totally your call IMO.

**Comment by jdorfman** [comment]
@XhmikosR has the best design sense out of us. Whatever he thinks

**Comment by XhmikosR** [comment]
If you send me the text I can put something together and ping you guys.

**Comment by jdorfman** [comment]
@XhmikosR my friend owns this service: https://www.iubenda.com/en/privacy-policy-generator/

I will get a free account.

**Comment by jdorfman** [comment]
@XhmikosR 

**options:**

**1:**
```
<a href="//www.iubenda.com/privacy-policy/74504147" class="iubenda-nostyle iubenda-embed" title="Privacy Policy">Privacy Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src = "//cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script>
```

**2:**
```
https://www.iubenda.com/privacy-policy/74504147
```

**3:**
```
<a href="//www.iubenda.com/privacy-policy/74504147" class="iubenda-nostyle iub-body-embed iubenda-embed" title="Privacy Policy">Privacy Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src = "//cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script>
```

**API**
```
http://www.iubenda.com/api/privacy-policy/74504147
```

https://www.iubenda.com/en/help/posts/78

Make sure to link back to `iubenda` since they hooked us up with a pro account.

**Comment by jdorfman** [comment]
@jmervine did I miss services? 

![image](https://user-images.githubusercontent.com/398230/34367812-c310c75a-ea63-11e7-8dde-b053bcc71339.png)

I don't think we need to add AWS since Heroku is hosted on AWS right?

**Comment by jmervine** [comment]
I wouldn’t mention any of this except maybe stack path, but I don’t know much about this side. 🤷🏻‍♂️

**Comment by jdorfman** [comment]
I checked with my buddy who is in this space and he says it should all be in there. In fact, we should technically have a separate cookie policy but I rather just wait to be told than add one of those annoying banners to our site.

**Comment by XhmikosR** [comment]
My main concern with this, is that I personally don't want to embed yet another third-party thing.

Can't we just get the text and we mention something like "Generated with foo(link)"?

**Comment by jdorfman** [comment]
@XhmikosR for sure that is why I gave you all the different options ;)

**Comment by jdorfman** [comment]
@XhmikosR what else do you need?

**Comment by XhmikosR** [comment]
Time for now, and the fact that I'm not sure with what solution I'll go.

The current one with embedding the script, leads to numerous CSP
violations. So since we don't plan to edit the page a lot, I think it would
be better if we just served any assets from our server, but I'm not sure
how to do it yet.

**Comment by jdorfman** [comment]
@XhmikosR just let me know what you need.

**Comment by XhmikosR** [comment]
1. We need to add some tests
2. I need a review from @jmervine about the approach I took with the CSS/JS files; this is so that we can add more there in the future

**Comment by jmervine** [comment]
Reviewed and approved.

**Comment by jdorfman** [comment]
@XhmikosR let's close this out. Do whatever you need to do to deploy it.

**Comment by XhmikosR** [comment]
@jdorfman: I already merged, but there's no need to hurry to close issues. It's confusing when the fix isn't there yet.
