### ISSUE TITLE
Change bootswatch.js script to use GitHub tags

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#948]
Currently we get the files from the live server. This is bad, because we don't follow any version control. So if one runs `npm run bootswatch 3.3.7` you will see the files will differ.

We should retrieve the GitHub tag instead.

@jmervine: if you make any progress just ping me.

**Comment by jdorfman** [comment]
@jmervine @XhmikosR what is happening with Bootswatch?

People are asking: https://twitter.com/orgbrat/status/968516215634321410

**Comment by XhmikosR** [comment]
@jdorfman: First of all, it's unrelated to this issue.

Secondly, it's in develop, not in master yet.
