### ISSUE TITLE
Serve CDN files with charset=UTF-8

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#949]
Not sure why we don't do this already...

We should serve any supported file types with a specified charset.

/CC @jdorfman

**Comment by jdorfman** [comment]
@petarpetrovic any ideas?

**Comment by petarpetrovic** [comment]
@XhmikosR can you give me an example file, both the origin URL and CDN URL?

cc @jdorfman

**Comment by jdorfman** [comment]
@petarpetrovic for intance:

```
> icurl https://cdn.jsdelivr.net/npm/jquery@3.2
content-type: application/javascript; charset=utf-8
```

```
> icurl https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js
content-type: application/javascript
```

I am sure we can set an EdgeRule to add it, but I think it is something that needs/should be enabled on the origin side.

**Comment by jmervine** [comment]
@jdorfman I could write a script crawl either [`config/_config.yml`](https://github.com/MaxCDN/bootstrap-cdn/tree/develop/config/_config.yml) or [`public`](https://github.com/MaxCDN/bootstrap-cdn/tree/develop/public) and adjust the content type of each element in s3. I don't love that approach though. It feels, risky.

Additionally, we could look at something like this: https://serverfault.com/questions/725562/recursively-changing-the-content-type-for-files-of-a-given-extension-on-amazon-s

**Comment by XhmikosR** [comment]
So we need to specify the file types ourselves ? If so I say we go with a
well know list of files like the one from html5 no apache config.

**Comment by jdorfman** [comment]
@jmervine I agree with you. It does seem risky for very little reward (IMO).

With that said, we have a few other S3 tasks:

 - `*.bootstrapcdn.com/index.html` -> redirect -> bootstrapcdn.com
 - EU replication

**Comment by XhmikosR** [comment]
Oh and add tests so that we don't hit this again without us noticing :)

**Comment by XhmikosR** [comment]
What do you mean little reward? This is wrong as any Unicode characters
won't be properly displayed without the right charset...

**Comment by jdorfman** [comment]
@XhmikosR without Googling, what is the advantage of adding `; charset=utf-8`?

**Comment by XhmikosR** [comment]
What I say in my previous message. This isn't an enhancement. It's a bug.

**Comment by jmervine** [comment]
That doesn’t answer the question. What’s the benefit of adding it. Not all bugs are worth fixing. Just trying to get the risk vs. reward.

**Comment by jdorfman** [comment]
I agree with @jmervine

**Comment by XhmikosR** [comment]
We are the only CDN that does this and you think it's ok?

As for if it answers the question, yes it does. If you don't want to
understand the importance that is something else.

**Comment by jdorfman** [comment]
@XhmikosR I respect the fact that the others do it, **BUT** we never get complaints from anyone because `charset=utf-8` is missing from the `Content-Type` header. So why add the extra 15 bytes to each request if we don't need to? @jmervine and I need to be convinced beyond "Google does it".

**Comment by XhmikosR** [comment]
Sorry, guys, this is just fundamentals for me. I honestly don't get why **you** don't see it.

It's the same way we set a charset for the HTML. Haven't you asked yourself why it's important to do it?

Any CSS or JS or text-served filetype may contain utf-8 characters. Without it, they won't show up correctly. And being we are a CDN, we need to play it safe.

Sure there are workarounds, at least for CSS files, like [`@charset`](https://developer.mozilla.org/en-US/docs/Web/CSS/%40charset), but like I said, why risk it? To save 15 bytes, is just the wrong reply, sorry. You could remove your "Say hello" header and save more.

Why no one has complained doesn't say anything. Similarly no one had complained that the latest bootlint didn't serve the map files right. **I** just noticed it.

If you want more to convince yourselves, just ask any server-experienced people, or just google.

PS. if you used nginx in the past, chances are you **were** using a charset then.

**Comment by jdorfman** [comment]
> You could remove your "Say hello" header and save more.

You got me there! 😂

Ok @XhmikosR you make a great point "why risk it?". 

@jmervine this should be part of an S3 improvement issue (1 not multiple) which will include the following:

- Fix `Content-Type` Headers
- Fix EU Replication
- Fix `https://maxcdn.bootstrapcdn.com` to load `index.html`
- Security/Permissions audit
- Check to make sure files are in sync with GH
- Update tests to account for new headers

**Comment by jmervine** [comment]
I did the perms audit. They’re good.

**Comment by coliff** [comment]
Agree with @XhmikosR - and FWIW - leaving off the UTF-8 header gives an error in the Sonarwhal Online Scanner. https://sonarwhal.com/scanner/

**Comment by jdorfman** [comment]
@jmervine please ignore the other bullet points, let's get the `content-type: application/javascript; charset=utf-8` header setup on S3.

I see this could be a good method: https://github.com/aws/aws-cli/issues/1346#issuecomment-333268233 e.g.

```
aws s3 sync --exclude "*" --include "*.js" --content-type "application/javascript; charset=utf-8"
```

**Comment by jmervine** [comment]
AFAIK, this will copy local files to s3 in the process. That should be safe but want to mention it.

**Comment by jmervine** [comment]
Want to expand on the lambda idea?

**Comment by jdorfman** [comment]
How is Lambda compared to S3's uptime/perf?

**Comment by XhmikosR** [comment]
I haven't used it yet myself, but it shouldn't really matter since the files will be cached by the CDN for a year. So only cold visits would request the files from S3.

**Comment by jdorfman** [comment]
From time to time all CDN's have to take a caching server out for maintenance or replace it altogether meaning the cache is stale/removed. Since we use a Pull Zone, if the origin (i.e. Lambda) is down, `5xx`'s will return.

**Comment by petarpetrovic** [comment]
@jdorfman we can always configure the Use Stale option in the pull zone's settings to return "stale" content in case of 5xx responses coming from the origin. In our case, the content wouldn't really be stale, we'd keep serving static assets as usual while the origin is down.

**Comment by XhmikosR** [comment]
Plus, you are assuming lambda will be down. I don't see why it would be down anyway.

Your call. Re-uploading everything with the proper charset is fine too, as long as we make a list before doing anything.

**Comment by XhmikosR** [comment]
For reference, from html5's boilerplate:

```apache
<IfModule mod_mime.c>
    AddCharset utf-8 .atom \
                     .bbaw \
                     .css \
                     .geojson \
                     .ics \
                     .js \
                     .json \
                     .jsonld \
                     .manifest \
                     .markdown \
                     .md \
                     .mjs \
                     .rdf \
                     .rss \
                     .topojson \
                     .vtt \
                     .webapp \
                     .webmanifest \
                     .xloc \
                     .xml
</IfModule>
```

**Comment by jmervine** [comment]
This goes back to why I want to serve the origin off wwwas opposed to S3. If the cdn is configured correctly, and doesn’t refresh content when the origin returns a non-200 status, there is no risk in it. This would give us full control over headers and the like, while allowing us to ensure they’re set correctly in our test suite. 

I’m down to update s3, and I know we’ve gone back and forth on this at length, but I just needed to say it again. 😝

**Comment by jdorfman** [comment]
TIL: `.topojson`

S3 is the way. 5 years with no issues. Sure there are drawbacks, and it would be easier to switch to www but reliablity+security = more sleep.

**Comment by jmervine** [comment]
Okay, before executing anything on S3, I decided to sync from S3 to a local branch. It looks like there's some files on s3 that aren't in github...
```
👉  🐧  ~/Development/bootstrap-cdn 👉  git st                                                                                                                                                                                            [ jmervine/s3-sync ⚡ | ☁  ]
?? public/debug/
?? public/js/jquery-1.9.1.min.js
?? public/twitter-bootstrap/3.3.7/js/bootstrap.bundle.js
?? public/twitter-bootstrap/3.3.7/js/bootstrap.bundle.min.js
?? public/twitter-bootstrap/4.0.0-alpha/js/npm.js
?? public/twitter-bootstrap/4.0.0-alpha/js/umd/
```

**Comment by XhmikosR** [comment]
As long as we don't have any other file types other than css and js it
looks ok.

**Comment by jmervine** [comment]
There’s at least one json fil as well.

**Comment by XhmikosR** [comment]
You can change that too then.

Also, don't do this without adding a script in the repo to replicate this. A simple script should suffice for the future.

**Comment by jdorfman** [comment]
@jmervine let's start with the older bootswatch files first then roll out to the others.

**Comment by jdorfman** [comment]
**Note:** Please don't ask for an ETA. This is a huge change that could affect millions of sites if rushed. We will be taking our time rolling this out. Thank you.

**Comment by jmervine** [comment]
2.1.0 done as a test. I’m going to do the rest in chunks (hopefully this weekend), I’ll include an order and check list here before starting.

**Comment by XhmikosR** [comment]
Did you clear the CDN cache? Otherwise the header won't show up until the file expires.

**Comment by XhmikosR** [comment]
Did you clear the CDN cache for the files you re-uploaded? Otherwise the header won't show up until the file expires.

**Comment by jdorfman** [comment]
Clearing

**Comment by jdorfman** [comment]
doesn't look like it:

```
> icurl https://maxcdn.bootstrapcdn.com/bootswatch/2.1.0/cerulean/bootstrap.min.css
HTTP/2 200 
date: Fri, 16 Feb 2018 16:00:06 GMT
content-type: text/css
...
x-cache: MISS
```
```
> icurl https://maxcdn.bootstrapcdn.com/bootswatch/2.1.0/cerulean/bootstrap.min.css
HTTP/2 200 
date: Fri, 16 Feb 2018 16:00:13 GMT
content-type: text/css
...
x-cache: HIT
```

**Comment by jmervine** [comment]
Progress
- [x] public/twitter-bootstrap/2.1.0
- [x] public/bootlint/0.2.0
- [x] public/bootlint
- [x] public/html5shiv
- [x] public/font-awesome/2.0
- [x] public/font-awesome/4.6.0
- [x] public/font-awesome
- [ ] public/bootswatch/2.1.0
- [ ] public/bootswatch
- [ ] public/twitter-bootstrap
- [ ] public/bootstrap

> All things flagged as done have been updated and verified.

----

@jdorfman I'm going to stop here and let it sit for a few days. If we have no error reports or issues, I'll finish it up.

**Comment by jdorfman** [comment]
Purge & QA:
- [x] https://maxcdn.bootstrapcdn.com/bootlint/0.14.2/bootlint.min.js
- [x] https://maxcdn.bootstrapcdn.com/bootlint/0.2.0/bootlint.min.js
- [x] https://maxcdn.bootstrapcdn.com/html5shiv/3.6.1/html5shiv.js
- [x] https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css
- [x] https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css

Looking good @jmervine =)

**Comment by jmervine** [comment]
Okay. I’ll hit the rest next chance I get. Later today or tomorrow.

**Comment by jmervine** [comment]
I have updated all files, once the CDN is purged, these tests should pass -- https://github.com/MaxCDN/bootstrapcdn/pull/978


@jdorfman This issue should be closed once the CDN has been purged.

**Comment by jdorfman** [comment]
@petarpetrovic tomorrow I am going to do a `purge all`. Can you tail the logs and make sure there are no errors?

**Comment by petarpetrovic** [comment]
@jdorfman absolutely. Just let me know 10ish minutes before purging on Slack so I can prepare everything on my end.

**Comment by jdorfman** [comment]
This issue is now complete. I would like to thank:
 
* @XhmikosR for bringing it to attention
* For taking the lead
* @petarpetrovic for his help on the CDN side
* @coliff for their comments

🤘
