### ISSUE TITLE
Consistent Branding

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrapcdn#956]
- [x] Update Twitter Colors/Theme
- [x] Update Readme (`s/Bootstrap CDN/BoostrapCDN/`)
- [ ] Update Repo name (`s/bootstrap-cdn/bootstrapcdn/`)

@XhmikosR @jmervine I am a little worried about updating the Repo name. I know GitHub does a good job of redirects, but what about tests and stuff?

![image](https://user-images.githubusercontent.com/398230/34650842-5670f6f2-f37c-11e7-9f4c-43b53fc04e6d.png)

![image](https://user-images.githubusercontent.com/398230/34650853-8a679664-f37c-11e7-884f-d01978ca8964.png)

![image](https://user-images.githubusercontent.com/398230/34650860-946ca956-f37c-11e7-8082-e009269d5ada.png)

**Comment by jdorfman** [comment]
Updated Topics
![image](https://user-images.githubusercontent.com/398230/34651026-5f17e362-f37f-11e7-84eb-bb522a68e042.png)

**Comment by jdorfman** [comment]
Added `/StackPath` to the repo description.

![image](https://user-images.githubusercontent.com/398230/34651060-b72585be-f37f-11e7-8ef8-ed852c9d98e8.png)

**Comment by jmervine** [comment]
Don’t use caps in the repo name. If you want to rename it use `bootstrapcdn`.

**Comment by XhmikosR** [comment]
Yup, agreed about the repo name with Josh.

The rest should be easy to do and generally everything should be OK. Any issues that might come up we can fix them.

I can make a PR later or tomorrow.

**Comment by jdorfman** [comment]
New Twitter theme

![image](https://user-images.githubusercontent.com/398230/34688784-232ff65c-f468-11e7-803c-517563bed7b7.png)
