### ISSUE TITLE
Change Google console verification to DNS TXT record

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#960]
It just makes more sense to have this linked to a higher level than what we have now.

**Comment by jdorfman** [comment]
@XhmikosR can you give the TXT record value? Assuming this is for `www` only?

**Comment by XhmikosR** [comment]
You can get it in the Google Search console, Cog button -> Verification details and click on the `Verify using a different method.` link.

**Comment by XhmikosR** [comment]
@petarpetrovic: any progress? This is pretty simple. You just need to add a DNS entry and ping me to remove the HTML `meta`.

**Comment by XhmikosR** [comment]
ping @petarpetrovic. This is just one DNS entry change.
