### ISSUE TITLE
Bootstrap 4.0.0 stable

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#964]
I'm opening this issue to discuss how to proceed and track what do to.

TODO:

- [x] Adapt frontend to remove the Beta warning
- [x] Merge config for bootstrap 3 and 4
- [x] Adapt frontend to only show the latest version
- [x] Adapt tests for the above stuff

**Comment by styfle** [comment]
It's here! http://blog.getbootstrap.com/2018/01/18/bootstrap-4/

**Comment by jdorfman** [comment]
@styfle yes it is on the CDN already. Just waiting for @XhmikosR to get back to a keyboard to update the site.

```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
```
```html
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
```

**Comment by jdorfman** [comment]
@XhmikosR see slack, had to push #966

**Comment by jdorfman** [comment]
@XhmikosR re-open if this isn't finished.
