### ISSUE TITLE
Some icons don't load on first page load (trademark, product)

### ISSUE THREAD

**Issue by mynameismosa** [MaxCDN/bootstrapcdn#974]
When using http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css or //maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css or older versions, at least two icons don't get load on first page load. I tried different versions, all the same.
Icons I tried: fa-trademark and fa-product-hunt.

Thanks for all!

**Comment by jdorfman** [comment]
hey @mynameismosa can you paste your code to a gist as well as posting a screenshot?

Thanks
