### ISSUE TITLE
Service Worker Support

### ISSUE THREAD

**Issue by bhubbard** [MaxCDN/bootstrapcdn#980]
I would love to see service worker support for the cdn. This could allow for local caching, and even offline support.

**Comment by jdorfman** [comment]
Interesting. Not my area of expertise so I have no idea how that would work. @XhmikosR care to chime in?

**Comment by XhmikosR** [comment]
Not something I have time to investigate and at this point I'm not even
sure it's possible for the CDN only. For the main site it's possible but it
would require preprocessing which again I'm not willing to spend any time
on unless the site is a purely static one.

That being said, if anyone makes a PR I can review it.

**Comment by jdorfman** [comment]
Closing for now.
