### ISSUE TITLE
S3 Tasks

### ISSUE THREAD

**Issue by jdorfman** [MaxCDN/bootstrapcdn#981]
Remaining S3 tasks

- [x] #949
- [ ]  EU replication
- [ ] `https://maxcdn.bootstrapcdn.com` -> redirect -> `https://www.bootstrapcdn.com`

**Comment by jdorfman** [comment]
@jmervine perfect. How many 403's are we seeing a day?

**Comment by jmervine** [comment]
After looking at 403 data — ~500 per second. The volume is too large to redirect to www.  Perhaps an empty file served on off the cdn?

**Comment by jmervine** [comment]
Or we just let them error. 

Additionally upon further reading. If the entire bucket was setup to serve static content these errors would be 404s. I need to dig in a bit but that might ensure that we don’t have to be concerned with perms for future uploads.

**Comment by jmervine** [comment]
Blog post on cross region replication. 

https://aws.amazon.com/blogs/aws/new-cross-region-replication-for-amazon-s3/

**Comment by jdorfman** [comment]
Sweet I will give that a shot tomorrow.

**Comment by jmervine** [comment]
I don’t mind looking at it as well. Just dropping it here for reference.

**Comment by jdorfman** [comment]
Give it a shot. We will most likely be moving to the Highwinds/StackPath platform for IPv6 support. They support a `backup origin` so I would like to have US as primary and EU as the backup.

![image](https://user-images.githubusercontent.com/398230/36679952-5c143398-1ac9-11e8-836f-0797b88490b3.png)

**Comment by jdorfman** [comment]
@jmervine any progress?

**Comment by XhmikosR** [comment]
@jdorfman @jmervine is this issue still valid?

**Comment by jdorfman** [comment]
@XhmikosR nah close it
