### ISSUE TITLE
Enable http/2 for the CDN

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#998]
Just opening this issue to track the http/2 progress on the CDN.

**Comment by petarpetrovic** [comment]
This is definitely planned for some time in the future, however, the current limitations on the new CDN infrastructure do not allow us to turn HTTP/2 back just yet. I'll be posting more updates to this thread as they become available.

**Comment by XhmikosR** [comment]
@petarpetrovic: is this now possible? Maybe we should switch to CDN4?

**Comment by XhmikosR** [comment]
This is now done, 🕺
